[package]
name = "td3d"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { package = "bevy", version = "0.14", features = ["wayland"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2"

[features]
default = ["bevy/dynamic_linking"]
